### ISSUE TITLE
linkstrings stage fails

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/PICCL#63]
The latest linkstrings stage in PICCL currently fails on a FoLiA processor error, possibly a regression caused by changes in foliatools/foliapy:

```
Command error:
  Converting test.foliacorrect.folia.xml
  Traceback (most recent call last):
    File "/usr/local/bin/foliatextcontent", line 8, in <module>
      sys.exit(main())
    File "/usr/local/lib/python3.8/dist-packages/foliatools/foliatextcontent.py", line 388, in main
      process(x)
    File "/usr/local/lib/python3.8/dist-packages/foliatools/foliatextcontent.py", line 292, in process
      linkstrings(element, cls, settings.debug)
    File "/usr/local/lib/python3.8/dist-packages/foliatools/foliatextcontent.py", line 92, in linkstrings
      markup = folia.TextMarkupString(element.doc, *stringtext, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/folia/main.py", line 4201, in __init__
      super(AbstractTextMarkup,self).__init__(doc, *args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/folia/main.py", line 659, in __init__
      kwargs = self.parsecommonarguments(doc, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/folia/main.py", line 851, in parsecommonarguments
      raise e
    File "/usr/local/lib/python3.8/dist-packages/folia/main.py", line 844, in parsecommonarguments
      self.processor = doc.getdefaultprocessor(annotationtype,self.set)
    File "/usr/local/lib/python3.8/dist-packages/folia/main.py", line 8298, in getdefaultprocessor
      raise NoDefaultError("No processor specified for <" + ANNOTATIONTYPE2XML[annotationtype] +  ">, but the presence of multiple declarations prevents assigning a default")
  folia.main.NoDefaultError: No processor specified for <str>, but the presence of multiple declarations prevents assigning a default
```

**Comment by proycon** [comment]
Fixed
